name: Node - SSH deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [stage*]
  pull_request:
    branches: [stage*]

jobs:
  build:
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.1']
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: 📂 Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          # ARGS: "-rltgoDzvO --delete"
          SOURCE: "./"
          REMOTE_HOST: 192.34.62.123
          REMOTE_USER: ableproadmin
          TARGET: public_html/codeigniter/stage/default
          EXCLUDE: "/node_modules/"
        
